name: E2E test

on:
  push:
    branches:
      - develop
      - trunk
  pull_request:
    branches:
      - develop
jobs:
  cypress:
    name: ${{ matrix.core.name }}
    runs-on: ubuntu-latest
    env:
      MICROSOFT_AZURE_ACCOUNT_NAME: ${{ secrets.MICROSOFT_AZURE_ACCOUNT_NAME }}
      MICROSOFT_AZURE_ACCOUNT_KEY: ${{ secrets.MICROSOFT_AZURE_ACCOUNT_KEY }}
      MICROSOFT_AZURE_CONTAINER: ${{ secrets.MICROSOFT_AZURE_CONTAINER }}
      MICROSOFT_AZURE_USE_FOR_DEFAULT_UPLOAD: ${{ secrets.MICROSOFT_AZURE_USE_FOR_DEFAULT_UPLOAD }}
    strategy:
      matrix:
        core:
          - {name: 'WP latest', version: 'latest'}
          - {name: 'WP minimum', version: 'WordPress/WordPress#5.7'}
          - {name: 'WP trunk', version: 'WordPress/WordPress#master'}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install dependencies
      run: npm install
    - name: Composer (optional)
      run: composer install
      continue-on-error: true
    - name: Build (optional)
      run: npm run build
      continue-on-error: true
    - name: Set the core version
      run: ./tests/bin/set-core-version.js ${{ matrix.core.version }}
    - name: Set up WP environment
      run: npm run env:start
    - name: Test
      run: npm run cypress:run
